### ISSUE TITLE
article précédent

### ISSUE THREAD

**Issue by thierry-bugeat** [Sergio-Muriel/tfe-rss#2]
Quand un article est ouvert, le bouton back a le même comportement que le bouton close. Il est donc impossible de passer à l'article précédent.

**Comment by Sergio-Muriel** [comment]
Corrigé sur la 0.2.6 :), merci!

**Comment by thierry-bugeat** [comment]
D'ailleurs, ca serait pas mal d'afficher quelque part le numéro de version. Et même de rajouter un lien vers le dépot github
